### PR TITLE
use wxt framework with react to build cross-browser extension

### PR DESCRIPTION
**Pull request by kunyuchen**
* Use [WXT](https://wxt.dev/) framework to build browser extension which could target Chrome, Firefox, Edge, etc
* Use React framework so that we can potentially reuse components across front-end and browser extensions

### CODE REVIEW

**Comment by TataKKKL** [comment]
@kunyuchen sure, that sounds good. I also just open-sourced this repo. Could you send a PR to remove Chrome extension-related code from https://github.com/PathOnAI/LiteWebAgent/tree/main/chrome_extension as well?
Are the configurations the same as https://github.com/PathOnAI/LiteWebAgent/blob/main/chrome_extension/README.md? I assume so.

**Comment by TataKKKL** [comment]
@kunyuchen , How about we make this repo a monorepo for frontend and chrome extension?

**Comment by kunyuchen** [comment]
@TataKKKL sounds good.
Working on: 1) cleaning up extension related code in [https://github.com/PathOnAI/LiteWebAgent/](https://github.com/PathOnAI/LiteWebAgent); 2) moving over and improving the README for browser extension.

**Comment by TataKKKL** [comment]
@kunyuchen sounds good!

@BRama10 and I will be modifying your chrome extension implementation tomorrow morning as well, and refactor the frontend at the same time as we mentioned

**Pull request merged**
